package main

// HELP content. Each section is a docPage in the paged viewer (left/right to
// switch sections, up/down to scroll). Copy is essay-style with **bold** key
// terms and `accent` highlights; all facts trace to the roster/mode/scoring
// source (playerBodies, gm.Rulesets, stats.go) - see helpReference notes.

func helpPages(cols int) []docPage {
	width := cols - 8
	if width < 20 {
		width = 20
	}
	prose := func(name string, lines []string) docPage {
		return docPage{name: name, body: proseLines(lines, width, docTheme)}
	}
	return []docPage{
		prose("CONTROLS", []string{
			"# DRIVING",
			"**W** / **S** drive forward and back.  **A** / **D** turn the hull.",
			"**Q** / **E** strafe sideways without turning.",
			"Hold **Shift** with any move key to `cruise` - the door latches that",
			"direction so you can let go and keep rolling (tap the key again to stop).",
			"",
			"# AIMING & FIRING",
			"**,** / **.** swing the turret left and right.  **up** / **dn** raise and",
			"lower the gun.  **C** snaps the turret back to center.",
			"**SPACE** fires your `primary`.  **B** fires your `secondary`.",
			"The arrow keys always aim, whatever your movement binds are.",
			"",
			"# MOVING THROUGH THE WORLD",
			"**ENTER** jumps.  Flyers (Butterfly, Falcon) `hold ENTER to hover`.",
			"A few characters `lunge forward` when they jump - a melee charge.",
			"",
			"# MATCH KEYS",
			"**TAB** toggles the top-down map and first-person views.",
			"**I** shows connection info.  **G** drops a carried flag (CTF).",
			"**ESC** leaves a match (it asks first); **BACKSPACE** leaves at once.",
			"",
			"Every key here is a default - remap any of them in `OPTIONS > CONTROLS`.",
		}),
		prose("CHARACTERS", []string{
			"# THE ROSTER",
			"Each character fights its own way - a different `signature weapon`, its own",
			"toughness and speed, and how it gets around (some `jump`, some `fly`, some",
			"`climb`). Pick the one that suits how you like to play. New here? The",
			"**TANK** is the balanced all-rounder and the best place to start.",
			"",
			"- **TANK** - the all-rounder: balanced armor, speed and turning. The honest pick, and the best place to learn.",
			"- **HUMANOID** - upright fighter, even frame; fires from the hand and slowly `regenerates` health.",
			"- **TIGER** - feline skirmisher: `pounce` in, `scratch` for a bleeding wound, then lick wounds to recover. Fast, high-regen.",
			"- **MANTIS** - raptorial forearms; agile, aggressive, and `leaps far`.",
			"- **GORILLA** - knuckle-walking bruiser; `bounds high` and lands a shockwave `pound` that knocks everyone around it back.",
			"- **MINOTAUR** - hammer bruiser; tap **B** to raise a `frontal barrier` that soaks fire, breaks, then recharges. Gore-charges on the jump.",
			"- **T-REX** - towering jaws and a `flame breath` cone. Slow, devastating.",
			"- **ELEPHANT** - anchor: trunk-`hook` a foe in close then gore with tusks; carries a regenerating shield buffer and **B**-sprays ally shields.",
			"- **TURTLE** - bunker: snapping bite up close; **B** tucks into the `shell` for a few invulnerable, immobile seconds.",
			"- **SCORPION** - glass sniper: a `hitscan laser` from the arched tail. Hits the instant you fire, but it's frail and slow.",
			"- **SERPENT** - cobra; raised hood, quick, spits `venom` that poisons.",
			"- **INSECT** - six-legged skitterer that `scales walls` (drive into one to climb); fast, with a deep magazine.",
			"- **OCTOPOD** - eight tentacles; `ink` slows whatever it hits.",
			"- **CRAB** - wide armored shell; lobs heavy `grenades` and drops mines.",
			"- **BUTTERFLY** - flying healer: `hold ENTER to hover`; a heal beam mends allies and heal-bombs splash support where they land.",
			"- **FALCON** - flying striker: hover and rain fast `talon` bolts, then a `gust` blast to shove foes off.",
			"- **STAG** - pack healer: a radial `aura` mends nearby allies; antler charge and a swift-bolt speed buff for a teammate.",
			"",
			"`Support` characters (Butterfly, Stag, Elephant) earn score by healing and",
			"shielding, not only by fragging - see the SCORING notes in PLAYER CARD.",
		}),
		prose("WEAPONS", []string{
			"# PRIMARY & SECONDARY",
			"**SPACE** fires your `primary`; **B** fires your `secondary`. Each",
			"character starts with the pair built for it, and power-ups on the",
			"map can swap your secondary mid-match. Weapons fall into a few families:",
			"",
			"# BOLTS",
			"Travelling shots you lead onto a moving target. The `cannon` is the plain",
			"workhorse; the `talon` is a fast light bolt; `venom` and `swift` carry an",
			"effect (poison, an ally speed boost) instead of raw punch.",
			"",
			"# BEAMS",
			"`Hitscan` - they land the instant you fire, no travel time. The scorpion's",
			"`laser` is the marksman's gun; the elephant's `hook` yanks a foe toward you.",
			"",
			"# LOBS",
			"Arcing throws that splash where they land: the `grenade` and the support",
			"`heal-bomb`. Great over cover, but you have to judge the arc.",
			"",
			"# MELEE & CONES",
			"Short-range bursts: the gorilla's `pound`, the minotaur's `hammer`, the",
			"t-rex `flame` cone, the elephant's `tusks`. Big numbers, but you have to",
			"close the distance.",
			"",
			"# SUPPORT",
			"`Medic` beams, `aura` pulses, `aegis` shield spray and `swift` boosts heal",
			"or buff allies. They do little to enemies - their value is keeping your",
			"team alive, and they score for it.",
		}),
		prose("GAME MODES", []string{
			"# DEATHMATCH",
			"Free-for-all fragging. `Most kills` before the clock runs out, or first to",
			"the frag limit. The purest test - no objective but the other tanks.",
			"",
			"# FLAG RUN",
			"A solo race: `collect every flag` scattered across the map before time",
			"expires. Finish fast for a big `time bonus`. This is the campaign spine.",
			"",
			"# CAPTURE THE FLAG",
			"Two teams. `Steal the enemy flag` and carry it home - but a capture only",
			"counts while `your own flag is safe` at base. Drop a carried flag with **G**.",
			"",
			"# SURVIVAL",
			"Co-op against `endless waves` of hunters. You share a pool of lives; the",
			"goal is simply to reach a `higher wave` than last time. Each wave banks score.",
			"",
			"# ELIMINATION",
			"Three lives each, no respawns after they're gone. `Last tank standing` wins.",
			"Plays patient and deadly.",
			"",
			"# KING OF THE HILL",
			"Hold the marked `zone` to bank points; first to the score wins. Comes in a",
			"solo free-for-all and a `two-team` variant.",
		}),
		prose("SOLO PLAY", []string{
			"# ONE CALLER VS THE BOTS",
			"Single player needs no arena and no network - just you and a field of",
			"bots. From the menu, highlight **SINGLE PLAYER** and use **<** / **>** to",
			"pick the mode, then **ENTER**.",
			"",
			"# DIFFICULTY",
			"Set the bot skill in `OPTIONS > DIFFICULTY`. Five tiers run from **EASY**",
			"to **ULTIMATE**; they change how far bots `see`, how fast they `react` and",
			"`track` you, how `accurate` their fire is, and how quickly they reload. On",
			"Ultimate they see the whole map, never miss, and `hunt power-ups`. Your",
			"choice is saved per caller.",
			"",
			"Solo scores are kept on `your own machine` (the PLAYER CARD and the local",
			"HIGH SCORES). They are not mixed into the global arena board.",
			"",
			"Difficulty also `weights your score`: a clear on a harder tier is worth",
			"more than the same run on Easy.",
		}),
		prose("ONLINE PLAY", []string{
			"# THE CROSS-BBS ARENA",
			"When your sysop points the door at an arena server, **ONLINE ARENA** lights",
			"up the menu. Pick it to drop into a `live match against callers from other",
			"boards`. Everyone is named `handle@BBS`, vouched by their home system.",
			"",
			"# THE LOBBY",
			"Between matches the arena sits in a lobby. Use **<** / **>** to `vote` on the",
			"next map and mode, then **ENTER** to lock your pick. When everyone is locked,",
			"the match starts; if no one votes, the server rotates the mode itself.",
			"",
			"# PARTIES",
			"The **PARTY** screen lets you team up. `Start a party` (named after you) and",
			"have a friend `join` it, or join theirs - in team modes the arena drops",
			"party members on the `same side`. One game means at most two parties, one",
			"per team. A party owner can boot a member with `/kick <player>`.",
			"",
			"Only real arena matches reach the `global` HIGH SCORES board.",
		}),
		prose("CUSTOM MAPS", []string{
			"# BUILD YOUR OWN ARENA",
			"`OPTIONS > MAP EDITOR` opens a 3D builder. You place the world from a fixed",
			"palette: **walls** and **platforms** for cover, **ramps** to climb,",
			"**spawn** and **pickup** points, and entities like **turrets**, **hazards**,",
			"**teleporters** and **trampolines**.",
			"",
			"# OBJECTIVES & RULES",
			"Drop the objective pieces a mode needs - `neutral flags` for Flag Run,",
			"`team flags` for CTF, a `hill zone` for King of the Hill. A map can carry its",
			"own **rules** (time limit, lives, target score) to override the mode default.",
			"",
			"# SHARING",
			"`Publish` a finished map to the arena and it joins the rotation other",
			"callers vote on in the lobby. Until then it stays yours to test.",
		}),
		prose("ABOUT", []string{
			"# SPECTRE",
			"A cross-BBS 3D tank game for the terminal: the world is rendered locally",
			"from pure game state on the wire - `never pixels` - so it stays sharp and",
			"cheap even over a dial-up-era link.",
			"",
			"# AUTHOR",
			"Built by **HM Derdok**.",
			"",
			"# SOURCE & ISSUES",
			"Repository: `github.com/hmderdoc/spekder`",
			"File bugs, request features, and grab newer client builds from the",
			"releases page there. When a newer build exists, the menu shows an",
			"**UPDATE AVAILABLE** banner; `OPTIONS > VERSION INFO` has the details.",
			"",
			"Thanks for playing. See you in the arena.",
		}),
	}
}
